### ISSUE TITLE
Adjust Average Block Time Value for 9.2.0

### ISSUE THREAD

**Issue by SlimePuppy** [CatcoinOfficial/CatcoinRelease#17]
The code has the same 10 minute target time that we've had from the start.  While this dual difficulty adjustment process runs better than any single routine we've tested to date, the average block time on testnet runs closer to 13 minutes (12-14 minutes typical).

I think we should reduce the target to 8 or 9 minutes and testnet the code - and adjust the target so that we get closer to a 10 minute average block time in the real world.

**Comment by zerodrama** [comment]
I think this is going to go away as we level off.

**Comment by SlimePuppy** [comment]
Zero called it.
