### ISSUE TITLE
OpenSSL, DER, Static Linking

### ISSUE THREAD

**Issue by SlimePuppy** [CatcoinOfficial/CatcoinRelease#20]
Right now, the Windows (and presumably Mac) wallets are static linked, while *nix is dynamic.  Considering that some versions of OpenSSL are known to break blockchains, should we tighten-up our dependencies and make all compiles static?

**Comment by zerodrama** [comment]
We should have instructions for building with static and dynamic linked binaries.

**Comment by SlimePuppy** [comment]
Maybe.  The time I joined we had static linking for Windows and Mac and dynamic linking for *nix.  Blak's reported that he hasn't yet been able to generate a static wallet on Ubuntu.
