### ISSUE TITLE
Mining CAT in Windows 10

### ISSUE THREAD

**Issue by alexnoxx** [CatcoinOfficial/CatcoinRelease#23]
Hi guys,
I'm trying to mining Catcoin but I'm having problems.
I have Windows 10 installed and my video card is AMD RX 560.
I am using bfgminer.
Is it possible to mine with that hardware and software? What steps do I have to take?

Thanks

**Comment by SlimePuppy** [comment]
That looks like a good card to mine with!  CAT is regular scrypt, so any of the how-tos one can find on the web will get you running.  Pools will normally have example set-ups - that'll be your best bet.
